apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: edw-apps
  namespace: argocd
spec:
  description: Applications managed by the EDW team
  sourceRepos:
    - '*'  # Later restrict to team-owned repos
  destinations:
    - namespace: edw
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
